// <auto-generated />
using System;
using HouseKeepingAccounting.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HouseKeepingAccounting.DAL.Migrations
{
    [DbContext(typeof(HouseContext))]
    [Migration("20200121114414_InitMigration")]
    partial class InitMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("HouseKeepingAccounting.DAL.Models.Counter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FactoryNumber")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HouseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("VerificationTimeOver")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HouseId")
                        .IsUnique();

                    b.ToTable("Counters");
                });

            modelBuilder.Entity("HouseKeepingAccounting.DAL.Models.House", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CityName")
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityName", "HomeNumber", "StreetName")
                        .IsUnique();

                    b.ToTable("Houses");
                });

            modelBuilder.Entity("HouseKeepingAccounting.DAL.Models.Indication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CounterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentIndication")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FillingTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("PreviousIndication")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CounterId");

                    b.ToTable("Indications");
                });

            modelBuilder.Entity("HouseKeepingAccounting.DAL.Models.Counter", b =>
                {
                    b.HasOne("HouseKeepingAccounting.DAL.Models.House", "House")
                        .WithOne("Counter")
                        .HasForeignKey("HouseKeepingAccounting.DAL.Models.Counter", "HouseId");
                });

            modelBuilder.Entity("HouseKeepingAccounting.DAL.Models.Indication", b =>
                {
                    b.HasOne("HouseKeepingAccounting.DAL.Models.Counter", null)
                        .WithMany("Indications")
                        .HasForeignKey("CounterId");
                });
#pragma warning restore 612, 618
        }
    }
}
